version: '3.8'

services:
  app_staging:
    build: .
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; yarn dev'
    entrypoint:
      - .docker/entrypoint.sh
    container_name: expense-api
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - .:/home/node/app
    depends_on:
      mysql_staging:
        condition: service_healthy
    environment:
      DATA_BASE_HOST: 'db_staging'

  mysql_staging:
    image: mysql
    container_name: db_staging
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: 'expense'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    expose:
      - "3306"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10