version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    depends_on:
      - mysql_staging

  mysql_staging:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'expenses'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
